name: My first Workflow

on : push

jobs: 
    first_job:
        runs_on: ubuntu-latest
        steps:
        - name : Welcome message
          run: echo "My first Github Actions Page"

        - name: List files
          run: ls

        - name: read files
          run: cat README.md
