name: My first Workflow

on : push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name : Checkout Repo
          uses: actions/checkout@v4

        - name: List files
          run: ls -lta 
        
        - name : Executing Shell scripts
          run: |   
            chmod +x shellscript.sh
            ./.github/workflows/shellscript.sh

        # - name: List files
        #   run: ls
          
        # - name: read files
        #   run: cat README.md
